#!/bin/bash
source /root/build-config.sh
source /root/build-common.sh
check_vars

if [[ -z "$1" ]]; then
	echo "Please supply version number"
	exit
else
	VERSION=$1
fi

function cleanup(){
	# Remove stale wine sockets
	rm -rf /tmp/.wine-*
}

cleanup

SOURCEDIR=/opt/wine-electrum/drive_c/electrum-grs/Electrum-GRS-$VERSION


cd $SOURCEDIR

$PYTHON "C:/PyInstaller/pyinstaller.py" -y "C:/electrum-grs/deterministic.spec"
cp /opt/wine-electrum/drive_c/electrum-grs/electrum-grs.nsi $SOURCEDIR/

echo "Running c:/electrum-grs/Electrum-GRS-$VERSION/electrum-grs.nsi for install"
xvfb-run wine c:\\"Program Files"\\NSIS\\makensis.exe -V1 c:/electrum-grs/Electrum-GRS-$VERSION/electrum-grs.nsi


cleanup
test -d /root/release-packages/Windows || mkdir -pv /root/release-packages/Windows
mv /opt/wine-electrum/drive_c/electrum-grs/Electrum-GRS-${VERSION}/dist/electrum-grs-setup.exe /root/release-packages/Windows/Electrum-GRS-${VERSION}-Windows-setup.exe
mv /opt/wine-electrum/drive_c/electrum-grs/Electrum-GRS-${VERSION}/dist/electrum-grs.exe /root/release-packages/Windows/Electrum-GRS-${VERSION}-Windows.exe
